name: cloudflared
base: core18
version: "0.2"
summary: cloudflared for snap
description: |
  enables you to use argo tunnel in snap based devices

grade: stable
confinement: strict
architectures:
  - build-on: arm64
  - build-on: amd64
parts:
  cloudflared:
    plugin: go
    source: https://github.com/cloudflare/cloudflared.git
    go-importpath: github.com/cloudflare/cloudflared/cmd/cloudflared
    build-packages:
      - build-essential
    stage-packages: [libstdc++6]
plugs:
  config-cloudflared:
    interface: personal-files
    read:
      - $HOME/.cloudflared/cert.pem
      - $HOME/.cloudflared/config.yml
apps:
  cloudflared:
    command: bin/cloudflared
    adapter: none
    plugs:
      - network
      - network-bind
      - config-cloudflared
  login:
    command: bin/cloudflared tunnel login
    plugs:
      - network
      - network-bind
      - config-cloudflared
  tunnel:
    command: bin/cloudflared tunnel --config $HOME/.cloudflared/config.yml --origincert $HOME/.cloudflared/cert.pem --no-autoupdate
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
      - config-cloudflared
