name: cloudflared
base: core18
version: "0.1"
summary: cloudflared for snap
description: |
  enables you to use argo tunnel in snap based devices

grade: stable
confinement: strict
architectures:
  - build-on: arm64
  - build-on: amd64
parts:
  cloudflared:
    plugin: go
    source: https://github.com/cloudflare/cloudflared.git
    build-packages:
      - build-essential
    stage-packages: [libstdc++6]
    override-build: |
      make cloudflared
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      mv cloudflared $SNAPCRAFT_PART_INSTALL/bin
plugs:
  config-cloudflared:
    interface: personal-files
    write:
      - $HOME/cloudflared-config/cert.pem
      - $HOME/cloudflared-config/config.yml
apps:
  login:
    command: bin/cloudflared tunnel login
    plugs:
      - network
      - network-bind
      - home
      - config-cloudflared
  tunnel:
    command: bin/cloudflared tunnel --config $HOME/cloudflared-config/config.yml --origincert $HOME/cloudflared-config/cert.pem --no-autoupdate
    daemon: notify
    restart-condition: on-failure
    start-timeout: 10s
    restart-delay: 10s
    plugs:
      - network
      - network-bind
      - home
      - config-cloudflared
