name: cloudflared
base: core18
version: "0.1"
summary: cloudflared for snap
description: |
  enables you to use argo tunnel in snap based devices

grade: stable
confinement: strict
architectures:
  - build-on: arm64
  - build-on: amd64
parts:
  cloudflared:
    plugin: go
    source: https://github.com/cloudflare/cloudflared.git
    build-packages:
      - gcc
      - g++
      - make
    stage-packages: [libstdc++6]
    override-build: |
      go install github.com/cloudflare/cloudflared/cmd/cloudflared
apps:
  login:
    command: cloudflared tunnel login
    plugs:
      - network
      - network-bind
  tunnel:
    command: cloudflared tunnel --config /home/$USER/.cloudflared/config.yml --origincert /home/$USER/.cloudflared/cert.pem --no-autoupdate
    daemon: simple
    restart-condition: always
    plugs:
      - network
      - network-bind
